FROM node:8.12.0-stretch as node
FROM ruby:2.5.1-slim-stretch
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential libpq-dev git

ENV YARN_VERSION 1.9.4
COPY --from=node /opt/yarn-v$YARN_VERSION /opt/yarn
COPY --from=node /usr/local/bin/node /usr/local/bin/
RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn && \
    ln -s /opt/yarn/bin/yarnpkg /usr/local/bin/yarnpkg

ARG path=/approot
RUN mkdir ${path}
WORKDIR ${path}
COPY ./Gemfile ${path}/Gemfile
COPY ./Gemfile.lock ${path}/Gemfile.lock

RUN bundle install
